### ISSUE TITLE
undefined symbol: Py_InitModule3

### ISSUE THREAD

**Issue by adityaxbiswas** [garydoranjr/pyemd#3]
Full error message:
from emd import emd
Traceback (most recent call last):

  File "<ipython-input-1114-8406a1f54f9f>", line 1, in <module>
    from emd import emd

  File "/home/aditya/anaconda3/lib/python3.6/site-packages/emd/__init__.py", line 4, in <module>
    from emd import emd

  File "/home/aditya/anaconda3/lib/python3.6/site-packages/emd/emd.py", line 7, in <module>
    from c_emd import _emd

ImportError: /home/aditya/anaconda3/lib/python3.6/site-packages/c_emd.cpython-36m-x86_64-linux-gnu.so: undefined symbol: Py_InitModule3

Here is a link I found discussing how the issue arises in how Python 3 initializes modules:
http://stackoverflow.com/questions/34871354/how-to-port-a-specific-c-module-to-python-3

**Comment by garydoranjr** [comment]
Unfortunately, the code does not support Python 3 at this time; maybe some day.

**Comment by komiljonov** [comment]
Look at this.
It helped me.

https://stackoverflow.com/questions/43621948/c-python-module-import-error-undefined-symbol-py-initmodule3-py-initmodu
